---
- name: Check current Logstash version.
  command: 'grep {{ os_version }} {{ os_soft_path }}/logstash/Gemfile.lock'
  register: os_logstash_current_version
  changed_when: false
  failed_when: false

- name: Install Logstash components.
  unarchive:
    src: '{{ os_soft_url }}/logstash/logstash-oss-with-opensearch-output-plugin-{{ os_logstash_version }}-linux-x64.tar.gz'
    dest: '{{ os_soft_path }}/logstash'
    owner: '{{ os_arg.user }}'
    group: '{{ os_arg.user }}'
    extra_opts: [--strip-components=1]
    remote_src: 'yes'
    validate_certs: 'no'
  register: os_logstash_update
  until: os_logstash_update is succeeded
  retries: 5
  delay: 2
  when: os_logstash_current_version.rc == 2 or os_version not in os_logstash_current_version.stdout
  notify: Restart Logstash service.