---
- name: Check private key exists.
  stat:
    path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/server.key'
  register: check_cert_keys

- name: Certificate Signing operation.
  block:
    - name: Creating certificate folder.
      file:
        dest: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl'
        state: 'directory'
        owner: '{{ os_arg.user }}'
        group: '{{ os_arg.user }}'
        mode: '600'
    - name: Selfsigned CA file transfer.
      copy:
        src: 'files/ssl/{{ item }}'
        dest: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl'
        owner: '{{ os_arg.user }}'
        group: '{{ os_arg.user }}'
        mode: '600'
      loop:
        - 'ca-cert.pem'
        - 'ca-key.pem'
    - name: "Generate an OpenSSL private key with PKCS #8 format."
      shell: 'openssl genpkey -out {{ os_soft_path }}/{{ os_cert_components }}/config/ssl/server.key -algorithm RSA -pkeyopt rsa_keygen_bits:4096'
    - name: Generate an OpenSSL Certificate Signing Request.
      openssl_csr:
        path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/server.csr'
        privatekey_path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/server.key'
        select_crypto_backend: 'cryptography'
        common_name: '{{ os_cluster| upper }}'
        subject_alt_name:
          - 'DNS:{{ ansible_hostname }}'
          - 'DNS:{{ ansible_fqdn }}'
          - 'DNS:{{ ansible_default_ipv4.address }}'
          - 'DNS:*.service.{{ datacenter }}.{{ domain }}'
          - 'IP:{{ ansible_default_ipv4.address }}'
        owner: '{{ os_arg.user }}'
        group: '{{ os_arg.user }}'
        mode: '600'
        state: 'present'
    - name: Generate an OpenSSL certificate signed with your own CA certificate.
      openssl_certificate:
        path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/server.crt'
        csr_path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/server.csr'
        ownca_path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/ca-cert.pem'
        ownca_privatekey_path: '{{ os_soft_path }}/{{ os_cert_components }}/config/ssl/ca-key.pem'
        select_crypto_backend: 'cryptography'
        ownca_not_after: '+7305d'
        provider: 'ownca'
        owner: '{{ os_arg.user }}'
        group: '{{ os_arg.user }}'
        mode: '600'
        state: 'present'
  when: not check_cert_keys.stat.exists or check_cert_keys.stat.size == 0
