---
- name: Exporter configure file transfer.
  template:
    src: '{{ item }}_exporter.default'
    dest: '/etc/default/{{ item }}_exporter'
    owner: '{{ os_arg.user }}'
    group: '{{ os_arg.user }}'
    mode: '0644'
  loop:
    - 'elasticsearch'
    - 'kibana'
    - 'logstash'
  notify:
    - Restart ElasticSearch exporter service.
    - Restart Kibana exporter service.
    - Restart LogStash exporter service.

- name: Install the ElasticSearch exporter packages.
  package:
    name: '{{ os_exporter_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Logstash & Kibana exporter program binary transfer.
  unarchive:
    src: '{{ item }}_exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: '{{ os_arg.user }}'
    group: '{{ os_arg.user }}'
    mode: '0755'
  loop:
    - 'logstash'
    - 'kibana'
  notify:
    - Restart LogStash exporter service.
    - Restart Kibana exporter service.

- name: Logstash & Kibana service file transfer.
  template:
    src: '{{ item }}_exporter.service'
    dest: '/lib/systemd/system'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'logstash'
    - 'kibana'
  notify:
    - Restart LogStash exporter service.
    - Restart Kibana exporter service.
