---
- name: Internal user password generator.
  set_fact:
    os_kibanaserver_pass: "{{ lookup('password', '/dev/shm/' + os_admin_pass + group_names[-1] + os_cluster + ':kibanaserver length=14 chars=ascii_letters,digits') }}"
    os_kibanaro_pass: "{{ lookup('password', '/dev/shm/' + os_admin_pass + group_names[-1] + os_cluster + ':kibanaro length=14 chars=ascii_letters,digits') }}"
    os_logstash_pass: "{{ lookup('password', '/dev/shm/' + os_admin_pass + group_names[-1] + os_cluster + ':logstash length=14 chars=ascii_letters,digits') }}"
    os_readall_pass: "{{ lookup('password', '/dev/shm/' + os_admin_pass + group_names[-1] + os_cluster + ':readall length=14 chars=ascii_letters,digits') }}"
    os_snapshotrestore_pass: "{{ lookup('password', '/dev/shm/' + os_admin_pass + group_names[-1] + os_cluster + ':snapshotrestore length=14 chars=ascii_letters,digits') }}"

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include installation tasks.
  include: 'install.yml'

- name: Install requirement python package.
  pip:
    name: '{{ item }}'
    state: 'present'
    extra_args: '--default-timeout=120 -i https://{{ os_pypi_url }}/pypi/simple/ --trusted-host {{ os_pypi_url }}'
  loop: '{{ os_python_dependent_packages }}'
  register: os_python_status
  until: os_python_status is succeeded
  retries: 5
  delay: 2

- name: Include certificate tasks.
  include: 'certificates.yml'
  loop:
    - 'opensearch'
    - 'opensearch-dashboards'
  loop_control:
    loop_var: os_cert_components

- name: Include configuration tasks.
  include: 'config.yml'

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Include exporter tasks.
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include Index State Management tasks.
  include: 'ISM.yml'
  when: os_servers[0] in ansible_default_ipv4.address
