---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add Opensearch exporter YUM repositories.
  yum_repository:
    name: '{{ os_exporter_repo_name }}'
    description: '{{ os_exporter_repo_name }} YUM repository'
    file: '{{ os_exporter_repo_name }}'
    baseurl: '{{ os_exporter_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'
